import type { Metadata } from "next";
import "./theme/lux/bootstrap.min.css";
import "./theme/icons/bootstrap-icons.css";
import "./globals.css";
import BootstrapClient from "@/components/BootstrapClient";
import Toaster from "@/components/custom_toast/Toaster";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <BootstrapClient />
        <Toaster />
      </body>
    </html>
  );
}
